### ISSUE TITLE
POA and Reporting delay

### ISSUE THREAD

**Issue by johnkane1** [CriminalInjuriesCompensationAuthority/apply-for-compensation-prototype#141]
The delay in reporting screen does not appear when historical dates are entered for POA (start/end dates).  Looking at the code in reporting-delay/routes.js it looks like the code is calculating only for a single incident and doesn't currently have logic for the month/year we collect for POAs.

**Comment by gavinwye** [comment]
@johnkane1 I've just had a look at this. There is code in `period-of-abuse-end/joutes.js` I don't fully understand what the code is doing but it looks like it _should_ be working.

Maybe @armoj could have a look at this?

**Comment by johnkane1** [comment]
This has been resolved by @armoj
